### ISSUE TITLE
menuOptions callback not returning rows after column sort

### ISSUE THREAD

**Issue by deely3** [nuxy/Tidy-Table#10]
My callback function works properly until I sort on a column header.  After sorting, the callback function parameter 'rows' is an empty array even though table rows have been selected.  Tried setting event breakpoints for mouse click in Chrome debugger, but that's not helping (just runs through the jQuery code).  I'm using this with jQuery 2.1.3.

**Comment by nuxy** [comment]
Is there code available, or some type of example that reproduces this issue?

That would help.

**Comment by deely3** [comment]
https://labs.mbrooks.info/demos/Tidy-Table/demo.html

1. Select a row or rows and click one of the callback options.  The number will correctly show how many rows were selected.
2. Sort on a column and the selected rows will automatically uncheck.
3. Then, select a row or rows (or leave unchecked - just make sure it's a different number of rows than previous) and click a callback option again.  This time the row count will incorrectly show the same number as what was selected before sorting.

Seems that the table passed into _getCheckedAsObj is the previous version of the table before sorting?

**Comment by nuxy** [comment]
Sorry for the delay on this.  Work has required a lot of my attention lately.

This issue is now resolved.

**Comment by deely3** [comment]
Thank you for the fix... Tidy-Table works great!

**Comment by deely3** [comment]
Hi nuxy, this seems to be related but may be a separate issue.  I am using a jQuery each to write two Tidy-tables to the page.  Before this fix, the callbacks correctly distinguished between the two tables, but now it only seems to reference either:  1) the last table created, or 2) the last table sorted.

https://jsfiddle.net/ce74nh6v/9/

**Comment by nuxy** [comment]
The issue you are experiencing (a result of a recent bug fix) has been resolved in the [2.1.2](https://github.com/nuxy/Tidy-Table/releases/tag/2.1.2) release.

Cheers.

**Comment by deely3** [comment]
Fantastic!  Thanks for the quick response and great code!
