### ISSUE TITLE
Wrong detection of jQuery version

### ISSUE THREAD

**Issue by dbackowski** [nuxy/Tidy-Table#7]
I use jQuery in version "1.11.0" and got error: "Tidy-Table requires jQuery 1.8.3 or greater."

```javascript
if (!window.jQuery || (window.jQuery && window.jQuery.fn.jquery < '1.8.3')) {
	throw new Error('Tidy-Table requires jQuery 1.8.3 or greater.');
}
```

This will raise error for version of jQuery "1.10.\*", "1.11.\*"

**Comment by nuxy** [comment]
This issue has been resolved in the [latest release](https://github.com/nuxy/Tidy-Table/releases/tag/2.0.5) v2.0.5

Closing this ticket.
